name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/shirtless_athletic_male_doing_biceps_workouts_with_one_dumbbell_grey_vignette_background_1.jpeg
  - assets/images/image_68.png
  - assets/images/image_65.png
  - assets/images/image_67.png
  - assets/images/image_64.png
  - assets/images/image_2.png
  - assets/images/image_63.png
  - assets/vectors/group_5_x2.svg
  - assets/vectors/rectangle_2_x2.svg
  - assets/vectors/frame_4_x2.svg
  - assets/vectors/group_111_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/box_5_x2.svg
  - assets/vectors/rectangle_61_x2.svg
  - assets/vectors/pyramid_11_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/ellipse_5_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/box_52_x2.svg
  - assets/vectors/rectangle_853_x2.svg
  - assets/vectors/group_22_x2.svg
  - assets/vectors/rectangle_62_x2.svg
  - assets/vectors/group_26_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/ellipse_6_x2.svg
  - assets/vectors/rectangle_22_x2.svg
  - assets/vectors/group_9_x2.svg
  - assets/images/shirtless_athletic_male_doing_biceps_workouts_with_one_dumbbell_grey_vignette_background_1.jpeg
  - assets/images/image_70.png
  - assets/images/young_athletic_woman_white_headphones_training_listening_music_street_outdoors_working_lower_body_out_mat_concept_healthy_lifestyle_open_air_sport_activity_weight_loss_1.jpeg
  - assets/images/image_69.png
  - assets/vectors/polygon_2_x2.svg
  - assets/vectors/polygon_21_x2.svg
  - assets/vectors/polygon_22_x2.svg
  - assets/vectors/group_11_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/group_21_x2.svg
  - assets/images/black_white_and_yellow_bold_fitness_logo_1_removebg_preview_11.png
  - assets/images/boxed_water_is_better_zqndcje_06_vm_unsplash_1.jpeg
  - assets/images/black_white_and_yellow_bold_fitness_logo_2.png
  - assets/vectors/rectangle_2496_x2.svg
  - assets/vectors/rectangle_2497_x2.svg
  - assets/vectors/rectangle_24991_x2.svg
  - assets/vectors/rectangle_2494_x2.svg
  - assets/vectors/rectangle_2498_x2.svg
  - assets/vectors/rectangle_2493_x2.svg
  - assets/vectors/rectangle_2495_x2.svg
  - assets/images/black_white_and_yellow_bold_fitness_logo_2.png
  - assets/vectors/rectangle_2499_x2.svg
  - assets/vectors/rectangle_24981_x2.svg
  - assets/vectors/rectangle_24982_x2.svg
  - assets/images/young_athletic_woman_white_headphones_training_listening_music_street_outdoors_working_lower_body_out_mat_concept_healthy_lifestyle_open_air_sport_activity_weight_loss_1.jpeg
  - assets/images/young_man_making_sport_exercises_home_1.jpeg
  - assets/images/black_white_and_yellow_bold_fitness_logo_1_removebg_preview_11.png
  - assets/images/anastase_maragos_izw_5_zlhmfd_4_unsplash_1.jpeg
  - assets/images/young_muscular_athlete_practicing_squats_gym_with_weight_1.jpeg
  - assets/images/athletic_woman_practicing_pushups_while_working_out_living_room_1.jpeg
  - assets/vectors/frame_41_x2.svg
  - assets/vectors/group_23_x2.svg
  - assets/vectors/rectangle_6_x2.svg
  - assets/vectors/ic_play_1_x2.svg
  - assets/vectors/rectangle_21_x2.svg
  - assets/vectors/group_121_x2.svg
  - assets/vectors/ic_play_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_12_x2.svg
  - assets/vectors/box_51_x2.svg

