// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrHHBe5JGdLlDsKnmkXgEam6qR1cATgE',
    appId: '1:811443581667:web:ccad480788a70c096f8bd6',
    messagingSenderId: '811443581667',
    projectId: 'gym-abtal-8941f',
    authDomain: 'gym-abtal-8941f.firebaseapp.com',
    storageBucket: 'gym-abtal-8941f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJkMmHfsBVe9KWKhalMEetiOfvxPS1nk',
    appId: '1:811443581667:android:679779fd0ca870c16f8bd6',
    messagingSenderId: '811443581667',
    projectId: 'gym-abtal-8941f',
    storageBucket: 'gym-abtal-8941f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx5QkmKF26IiFC7drveuaHDQAHaJjsfX8',
    appId: '1:811443581667:ios:65a0a2169cffb87f6f8bd6',
    messagingSenderId: '811443581667',
    projectId: 'gym-abtal-8941f',
    storageBucket: 'gym-abtal-8941f.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx5QkmKF26IiFC7drveuaHDQAHaJjsfX8',
    appId: '1:811443581667:ios:65a0a2169cffb87f6f8bd6',
    messagingSenderId: '811443581667',
    projectId: 'gym-abtal-8941f',
    storageBucket: 'gym-abtal-8941f.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcrHHBe5JGdLlDsKnmkXgEam6qR1cATgE',
    appId: '1:811443581667:web:661b3f310078dc556f8bd6',
    messagingSenderId: '811443581667',
    projectId: 'gym-abtal-8941f',
    authDomain: 'gym-abtal-8941f.firebaseapp.com',
    storageBucket: 'gym-abtal-8941f.appspot.com',
  );
}
